{% set name = "sklearn-crfsuite" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 0449323977a49303903b9c50de47ce88f68cb6cc01c50b8b728d33fc3dc2883a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - python-crfsuite >=0.8.3
    - six
    - tabulate
    - tqdm >=2.0

test:
  imports:
    - sklearn_crfsuite

about:
  home: "https://github.com/TeamHG-Memex/sklearn-crfsuite"
  license: MIT
  license_family: MIT
  license_file: # No packaged license file, issue here: https://github.com/TeamHG-Memex/sklearn-crfsuite/issues/48
  summary: "CRFsuite (python-crfsuite) wrapper which provides interface simlar to scikit-learn"
  doc_url: https://sklearn-crfsuite.readthedocs.io/en/latest/
  dev_url: https://github.com/TeamHG-Memex/sklearn-crfsuite
  description: |
    sklearn-crfsuite is thin a CRFsuite (python-crfsuite) wrapper which provides scikit-learn-compatible
    sklearn_crfsuite.CRF estimator: you can use e.g. scikit-learn model selection utilities (cross-validation,
    hyperparameter optimization) with it, or save/load CRF models using joblib.

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
